export default {
    signIn: 'Sign In!',
    signUp:'Sign Up!',
    toBeThisWeek: 'To Be This Week?',
    rankYourTo: "Rank your To-Do's on a Scale of 1-5 ",
    continue: 'Continue',
    addNumber: 'Add your phone number:',
    verificationText: 'Enter your verification code:',
    invalidText: 'You do not seem to have an account - please check us out at <URL>',
    invalidTextNew:
        'Hmm, we don’t seem to have that phone number in our records. If you don’t already have a Donzio account, you or your company administrator can go to',
    invalidTextNew1: 'to create one!',
    letsRankTheseDemo_1: "Next We'll Rank Your",
    letsRankTheseDemo_2: 'Choices On A Scale',
    letsRankTheseDemo_3: 'From 1-5.',
    letsRankThese: "Let's Rank These!",
    letsRankTheseSimple: "Let's Rank These",
    happySunday: 'Happy Sunday!',
    complete: 'Complete',
    beforeComplete: 'Type Your "TO BE"s above',
    whatDoYouWant: 'Who Do You Want',
    toBe: 'TO BE ',
    ThisWeek: 'This Week?',
    greatWork: 'Great Work!',
    whatMustYou: 'What Must You',
    accThisWeek: 'Accomplish This Week?',
    addNew: 'Add New',
    myToDoS: "My To-Do's:",
    completeToDo: 'Complete To Do List',
    completeToDoList: 'Complete To-Do List',
    thisWeeksTask: "This Week's Tasks",
    hereOurSugg: "Here's Our Suggestions:",
    delegate: 'Delegate',
    tapToAssign: 'Tap to assign a team member',
    delete: 'Delete',
    parkLot: 'Parking Lot',
    delay: 'Delay',
    month: 'Months',
    week: 'Weeks',
    day: 'Days',
    enterAmmOfTime: 'Enter amount of time to delay project.',
    setting: 'Settings',
    teamMember: 'Team Members',
    configurableOptions: 'Configurable options',
    delegatedItems: 'Delegated Items',
    colinTeam: "Colin Sprake's Team",
    yourTeamMember: 'Your team members',
    addNewTeamMember: 'Add new Team Member',
    inviteNumber: 'Invite by phone number',
    invite: 'Invite',
    yourTask: 'Your Tasks',
    onceCompText: 'Once completed, check off the task!',
    delegateItem: 'Delegated Items',
    allToDo: "All To Do's",
    deleteMessage: 'Are you sure you want to delete this task?',
    pushTaskMessage: 'Who would you like to push this task to ?',
    Options: 'Options',
    Prioritize: 'Prioritize',
    over: 'over',
    restoreButton: 'Restore Default Settings',
    typeObove: 'Type Your "TO BE"s above',
    greatWorkMiddleHeader: 'What must you accomplish this Week?',
    myToDo: "My To Do's",
    sampleDelegateItemText:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    delegateHeaderText: 'Push delegated item to a team member',
    teamMembers: 'Team Members',
    yourItems: 'Your Items',
    yourTasksMiddleHeader: 'Once completed, check off the task!',
    tasks: 'Tasks',
    completeToDoList: 'Complete To Do List',
    removeUser: 'Remove User',
    currentToDo: "Current To Do's:",
    role: 'Role:',
    thatsMakeSense: 'That Makes Sense!',
    notRecordFound: 'No records found',
    orderDoTitle: 'DO IN THIS ORDER:',
    orderDelegateTitle: 'Delegate',
    orderDelayTitle: 'Delay',
    orderDeleteTitle: 'Delete',
    dollarTopTextDemo: '1-Dollar sign = slowest path to money or income',
    dollarMiddleTextDemo:
        '5-dollar signs means the most rapid path to income or maintaining income (looking after a disgruntled client, etc.).',
    dollarBottomTextDemo: "Of cource, it's either 1,2,3,4 or 5 Dollars!",
    heartTopTextDemo: '1-Heart sign = thing you list like doing, does not fill your cup',
    heartMiddleTextDemo: '5-Heart signs means that you love doing it, it fills your cup and you could do it all day.',
    heartBottomTextDemo: "Of cource, it's either 1,2,3,4 or 5 Hearts!",
    textInputErrorMsg: 'Please fill up this field',
    noRecordFound: 'No records found',
    pushDelegateItemToTeam: 'Push delegated item to a team member',
    prevDeleted: 'Previously Deleted Items',
    back: 'Back',
    ListingData: 'Listing Data',
    errorMsgDelayText: 'Task should not be Delay more than 66 days',
    errorTeamMsg: 'No team members yet',
    enterNumber:'Enter your phone number along with country code .'
};
